import { createElement } from '@lwc/engine-dom';
import RenderedList_day21_1 from 'c/renderedList_day21_1';

describe('c-rendered-list-day21-1', () => {
    afterEach(() => {
        // The jsdom instance is shared across test cases in a single file so reset the DOM
        while (document.body.firstChild) {
            document.body.removeChild(document.body.firstChild);
        }
    });

    it('TODO: test case generated by CLI command, please fill in test logic', () => {
        // Arrange
        const element = createElement('c-rendered-list-day21-1', {
            is: RenderedList_day21_1
        });

        // Act
        document.body.appendChild(element);

        // Assert
        // const div = element.shadowRoot.querySelector('div');
        expect(1).toBe(1);
    });
});