import { createElement } from '@lwc/engine-dom';
import ToDoApplication_miniProject_22 from 'c/toDoApplication_miniProject_22';

describe('c-to-do-application-mini-project-22', () => {
    afterEach(() => {
        // The jsdom instance is shared across test cases in a single file so reset the DOM
        while (document.body.firstChild) {
            document.body.removeChild(document.body.firstChild);
        }
    });

    it('TODO: test case generated by CLI command, please fill in test logic', () => {
        // Arrange
        const element = createElement('c-to-do-application-mini-project-22', {
            is: ToDoApplication_miniProject_22
        });

        // Act
        document.body.appendChild(element);

        // Assert
        // const div = element.shadowRoot.querySelector('div');
        expect(1).toBe(1);
    });
});