import { createElement } from '@lwc/engine-dom';
import DynamicCss_day21_2 from 'c/dynamicCss_day21_2';

describe('c-dynamic-css-day21-2', () => {
    afterEach(() => {
        // The jsdom instance is shared across test cases in a single file so reset the DOM
        while (document.body.firstChild) {
            document.body.removeChild(document.body.firstChild);
        }
    });

    it('TODO: test case generated by CLI command, please fill in test logic', () => {
        // Arrange
        const element = createElement('c-dynamic-css-day21-2', {
            is: DynamicCss_day21_2
        });

        // Act
        document.body.appendChild(element);

        // Assert
        // const div = element.shadowRoot.querySelector('div');
        expect(1).toBe(1);
    });
});