import { createElement } from '@lwc/engine-dom';
import ConditionalRendering_day_21 from 'c/conditionalRendering_day_21';

describe('c-conditional-rendering-day-21', () => {
    afterEach(() => {
        // The jsdom instance is shared across test cases in a single file so reset the DOM
        while (document.body.firstChild) {
            document.body.removeChild(document.body.firstChild);
        }
    });

    it('TODO: test case generated by CLI command, please fill in test logic', () => {
        // Arrange
        const element = createElement('c-conditional-rendering-day-21', {
            is: ConditionalRendering_day_21
        });

        // Act
        document.body.appendChild(element);

        // Assert
        // const div = element.shadowRoot.querySelector('div');
        expect(1).toBe(1);
    });
});